name: Cherry Pick

on:
  workflow_dispatch:
    inputs:
      shas:
        description: "Comma-separated list of commit SHAs to cherry-pick"
        required: true
        type: string

jobs:
  cherry_pick:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Cherry-pick commits
        env:
          SHAS: ${{ github.event.inputs.shas }}
        run: |
          echo "Cherry-picking the following SHAs: $SHAS"
          for sha in $(echo $SHAS | tr ',' ' '); do
            echo "Cherry-picking $sha"
            git cherry-pick $sha || { echo "::error ::Failed to cherry-pick $sha"; exit 1; }
          done

      - name: Push changes
        run: |
          git push origin HEAD
