name: Copy Commits from caredev to merge

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *" # Runs every hour; adjust as needed

jobs:
  copy-commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # important: fetch full history

      - name: Set up Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Fetch all branches
        run: git fetch origin +refs/heads/*:refs/remotes/origin/*

      - name: Checkout merge branch
        run: git checkout merge

      - name: Ensure caredev branch exists locally
        run: git checkout -b caredev origin/caredev

      - name: Rebase caredev onto merge
        run: git rebase caredev
        continue-on-error: true

      - name: Push changes to merge branch
        run: git push origin merge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
