name: Sync caredev → merge

on:
  repository_dispatch:
    types: [push_caredev_to_merge]
  schedule:
    - cron: "0 * * * *" # Runs every hour; adjust as needed

jobs:
  sync-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Fetch all branches
        run: git fetch origin +refs/heads/*:refs/remotes/origin/*

      - name: Checkout merge branch
        run: git checkout merge

      - name: Reset merge branch to caredev
        run: |
          git reset --hard origin/caredev

      - name: Push updated merge branch
        run: git push origin merge --force
